version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db-migrate:
    image: postgres:15
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/migrations:/migrations:ro
    entrypoint: ["bash","-c","for f in /migrations/*.sql; do psql -h postgres -U $$POSTGRES_USER -d postgres -f $$f || exit 1; done"]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: "no"

  redis:
    image: redis:7-alpine
    restart: always

  n8n:
    image: n8nio/n8n:1.43
    restart: always
    environment:
      N8N_HOST: "localhost"
      N8N_PORT: 5678
      N8N_PROTOCOL: "http"
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_DATABASE_TYPE: "postgresdb"
      N8N_DATABASE_HOST: "postgres"
      N8N_DATABASE_PORT: 5432
      N8N_DATABASE_USER: ${POSTGRES_USER}
      N8N_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      N8N_DATABASE_NAME: ${POSTGRES_DB}
      N8N_EMAIL_MODE: "smtp"
      N8N_SMTP_HOST: "localhost"
      EXECUTIONS_PROCESS: "main"
      QUEUE_BULL_REDIS_HOST: "redis"
      N8N_IMPORT_EXPORT_OVERWRITE: "true"
      N8N_LOG_LEVEL: "debug"
      N8N_LOG_OUTPUT: "json"
    ports:
      - "5678:5678"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/home/node/.n8n/import:ro

volumes:
  postgres_data:
  n8n_data: