version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-migrate:
    image: migrate/migrate:latest
    entrypoint: ["sh", "-c", "until pg_isready -h postgres -U postgres; do sleep 1; done; migrate -path /migrations -database 'postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable' up"]
    volumes:
      - ./db/migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
  redis:
    image: redis:7-alpine
    restart: always

  n8n:
    image: n8nio/n8n:1.43.0
    restart: always
    environment:
      N8N_HOST: "localhost"
      N8N_PORT: 5678
      N8N_PROTOCOL: "http"
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_DATABASE_TYPE: "postgresdb"
      N8N_DATABASE_HOST: "postgres"
      N8N_DATABASE_PORT: 5432
      N8N_DATABASE_USER: ${POSTGRES_USER}
      N8N_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      N8N_DATABASE_NAME: ${POSTGRES_DB}
      N8N_EMAIL_MODE: "smtp"
      N8N_SMTP_HOST: "localhost"
      EXECUTIONS_PROCESS: "main"
      QUEUE_BULL_REDIS_HOST: "redis"
      N8N_IMPORT_EXPORT_OVERWRITE: "true"
      N8N_LOG_LEVEL: "debug"
      N8N_LOG_OUTPUT: "json"
    ports:
      - "5678:5678"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
      - db-migrate
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/home/node/.n8n/import:ro

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  metrics:
    build:
      context: ./metrics
    ports:
      - "9464:9464"

volumes:
  pgdata:
  n8n_data:
  prometheus_data: