name: alpha-smoke
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: pw-1.44.0
      - uses: docker/setup-buildx-action@v3
      - run: "DEBIAN_FRONTEND=noninteractive apt-get -qq update && apt-get -qq install -y jq"

  trivy-scan:
    if: always()
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
